// Package utmapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package utmapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	. "github.com/rootxkit/uspace-core/f3548"
)

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// StdClient which conforms to the OpenAPI3 specification for this service.
type StdClient struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*StdClient) error

// Creates a new StdClient, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*StdClient, error) {
	// create a client with sane default values
	client := StdClient{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *StdClient) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *StdClient) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetUssAvailability Get availability status of a USS.
	//
	// Corresponds with GET /dss/v1/uss_availability/{uss_id} (the `GetUssAvailability` operationId).
	GetUssAvailability(ctx context.Context, ussId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SetUssAvailabilityWithBody Set availability status of a USS.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /dss/v1/uss_availability/{uss_id} (the `SetUssAvailability` operationId).
	SetUssAvailabilityWithBody(ctx context.Context, ussId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SetUssAvailability Set availability status of a USS.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PUT /dss/v1/uss_availability/{uss_id} (the `SetUssAvailability` operationId).
	SetUssAvailability(ctx context.Context, ussId string, body SetUssAvailabilityJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetUssAvailability Get availability status of a USS.
//
// Corresponds with GET /dss/v1/uss_availability/{uss_id} (the `GetUssAvailability` operationId).
func (c *StdClient) GetUssAvailability(ctx context.Context, ussId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUssAvailabilityRequest(c.Server, ussId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SetUssAvailabilityWithBody Set availability status of a USS.
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /dss/v1/uss_availability/{uss_id} (the `SetUssAvailability` operationId).
func (c *StdClient) SetUssAvailabilityWithBody(ctx context.Context, ussId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetUssAvailabilityRequestWithBody(c.Server, ussId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SetUssAvailability Set availability status of a USS.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PUT /dss/v1/uss_availability/{uss_id} (the `SetUssAvailability` operationId).
func (c *StdClient) SetUssAvailability(ctx context.Context, ussId string, body SetUssAvailabilityJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSetUssAvailabilityRequest(c.Server, ussId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetUssAvailabilityRequest constructs an http.Request for the GetUssAvailability method
func NewGetUssAvailabilityRequest(server string, ussId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "uss_id", ussId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/dss/v1/uss_availability/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSetUssAvailabilityRequest calls the generic SetUssAvailability builder with application/json body
func NewSetUssAvailabilityRequest(server string, ussId string, body SetUssAvailabilityJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSetUssAvailabilityRequestWithBody(server, ussId, "application/json", bodyReader)
}

// NewSetUssAvailabilityRequestWithBody constructs an http.Request for the SetUssAvailability method, with any body, and a specified content type
func NewSetUssAvailabilityRequestWithBody(server string, ussId string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "uss_id", ussId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/dss/v1/uss_availability/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *StdClient) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *StdClient) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetUssAvailabilityWithResponse Get availability status of a USS.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /dss/v1/uss_availability/{uss_id} (the `GetUssAvailability` operationId).
	GetUssAvailabilityWithResponse(ctx context.Context, ussId string, reqEditors ...RequestEditorFn) (*GetUssAvailabilityReply, error)

	// SetUssAvailabilityWithBodyWithResponse Set availability status of a USS.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /dss/v1/uss_availability/{uss_id} (the `SetUssAvailability` operationId).
	SetUssAvailabilityWithBodyWithResponse(ctx context.Context, ussId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SetUssAvailabilityReply, error)

	// SetUssAvailabilityWithResponse Set availability status of a USS.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /dss/v1/uss_availability/{uss_id} (the `SetUssAvailability` operationId).
	SetUssAvailabilityWithResponse(ctx context.Context, ussId string, body SetUssAvailabilityJSONRequestBody, reqEditors ...RequestEditorFn) (*SetUssAvailabilityReply, error)
}

type GetUssAvailabilityReply struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *UssAvailabilityStatusResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *ErrorResponse
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *ErrorResponse
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *ErrorResponse
	// JSON429 the response for an HTTP 429 `application/json` response
	JSON429 *ErrorResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetUssAvailabilityReply) GetJSON200() *UssAvailabilityStatusResponse {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r GetUssAvailabilityReply) GetJSON400() *ErrorResponse {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetUssAvailabilityReply) GetJSON401() *ErrorResponse {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r GetUssAvailabilityReply) GetJSON403() *ErrorResponse {
	return r.JSON403
}

// GetJSON429 returns the response for an HTTP 429 `application/json` response
func (r GetUssAvailabilityReply) GetJSON429() *ErrorResponse {
	return r.JSON429
}

// GetBody returns the raw response body bytes
func (r GetUssAvailabilityReply) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetUssAvailabilityReply) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUssAvailabilityReply) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetUssAvailabilityReply) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type SetUssAvailabilityReply struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *UssAvailabilityStatusResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *ErrorResponse
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *ErrorResponse
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *ErrorResponse
	// JSON429 the response for an HTTP 429 `application/json` response
	JSON429 *ErrorResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r SetUssAvailabilityReply) GetJSON200() *UssAvailabilityStatusResponse {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r SetUssAvailabilityReply) GetJSON400() *ErrorResponse {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r SetUssAvailabilityReply) GetJSON401() *ErrorResponse {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r SetUssAvailabilityReply) GetJSON403() *ErrorResponse {
	return r.JSON403
}

// GetJSON429 returns the response for an HTTP 429 `application/json` response
func (r SetUssAvailabilityReply) GetJSON429() *ErrorResponse {
	return r.JSON429
}

// GetBody returns the raw response body bytes
func (r SetUssAvailabilityReply) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r SetUssAvailabilityReply) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SetUssAvailabilityReply) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SetUssAvailabilityReply) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetUssAvailabilityWithResponse Get availability status of a USS.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /dss/v1/uss_availability/{uss_id} (the `GetUssAvailability` operationId).
func (c *ClientWithResponses) GetUssAvailabilityWithResponse(ctx context.Context, ussId string, reqEditors ...RequestEditorFn) (*GetUssAvailabilityReply, error) {
	rsp, err := c.GetUssAvailability(ctx, ussId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUssAvailabilityReply(rsp)
}

// SetUssAvailabilityWithBodyWithResponse Set availability status of a USS.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /dss/v1/uss_availability/{uss_id} (the `SetUssAvailability` operationId).
func (c *ClientWithResponses) SetUssAvailabilityWithBodyWithResponse(ctx context.Context, ussId string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SetUssAvailabilityReply, error) {
	rsp, err := c.SetUssAvailabilityWithBody(ctx, ussId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetUssAvailabilityReply(rsp)
}

// SetUssAvailabilityWithResponse Set availability status of a USS.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /dss/v1/uss_availability/{uss_id} (the `SetUssAvailability` operationId).
func (c *ClientWithResponses) SetUssAvailabilityWithResponse(ctx context.Context, ussId string, body SetUssAvailabilityJSONRequestBody, reqEditors ...RequestEditorFn) (*SetUssAvailabilityReply, error) {
	rsp, err := c.SetUssAvailability(ctx, ussId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSetUssAvailabilityReply(rsp)
}

// ParseGetUssAvailabilityReply parses an HTTP response from a GetUssAvailabilityWithResponse call
func ParseGetUssAvailabilityReply(rsp *http.Response) (*GetUssAvailabilityReply, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUssAvailabilityReply{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UssAvailabilityStatusResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	}

	return response, nil
}

// ParseSetUssAvailabilityReply parses an HTTP response from a SetUssAvailabilityWithResponse call
func ParseSetUssAvailabilityReply(rsp *http.Response) (*SetUssAvailabilityReply, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SetUssAvailabilityReply{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UssAvailabilityStatusResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	}

	return response, nil
}
