//go:build go1.22

// Package ridapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package ridapi

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	. "github.com/rootxkit/uspace-core/f3411"
)

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// StdClient which conforms to the OpenAPI3 specification for this service.
type StdClient struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*StdClient) error

// Creates a new StdClient, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*StdClient, error) {
	// create a client with sane default values
	client := StdClient{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *StdClient) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *StdClient) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// SearchIdentificationServiceAreas /dss/identification_service_areas
	//
	// Retrieve all Identification Service Areas in the DAR for a given area during the given time.  Note that some Identification Service Areas returned may lie entirely outside the requested area.
	//
	// Corresponds with GET /dss/identification_service_areas (the `SearchIdentificationServiceAreas` operationId).
	SearchIdentificationServiceAreas(ctx context.Context, params *SearchIdentificationServiceAreasParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateSubscriptionWithBody /dss/subscriptions/{id}
	//
	// Create a subscription.  This call will fail if a Subscription with the same ID already exists.
	//
	// Subscription notifications are only triggered by (and contain full information of) changes to, creation of, or deletion of, Entities referenced by or stored in the DSS; they do not involve any data transfer (such as remote ID telemetry updates) apart from Entity information.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /dss/subscriptions/{id} (the `CreateSubscription` operationId).
	CreateSubscriptionWithBody(ctx context.Context, id SubscriptionUUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateSubscription /dss/subscriptions/{id}
	//
	// Create a subscription.  This call will fail if a Subscription with the same ID already exists.
	//
	// Subscription notifications are only triggered by (and contain full information of) changes to, creation of, or deletion of, Entities referenced by or stored in the DSS; they do not involve any data transfer (such as remote ID telemetry updates) apart from Entity information.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PUT /dss/subscriptions/{id} (the `CreateSubscription` operationId).
	CreateSubscription(ctx context.Context, id SubscriptionUUID, body CreateSubscriptionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteSubscription /dss/subscriptions/{id}/{version}
	//
	// Delete a subscription.
	//
	// Corresponds with DELETE /dss/subscriptions/{id}/{version} (the `DeleteSubscription` operationId).
	DeleteSubscription(ctx context.Context, id SubscriptionUUID, version string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateSubscriptionWithBody /dss/subscriptions/{id}/{version}
	//
	// Update a Subscription.  The full content of the existing Subscription will be replaced with the provided information as only the most recent version is retained.
	//
	// Subscription notifications are only triggered by (and contain full information of) changes to, creation of, or deletion of, Entities referenced by or stored in the DSS; they do not involve any data transfer (such as remote ID telemetry updates) apart from Entity information.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /dss/subscriptions/{id}/{version} (the `UpdateSubscription` operationId).
	UpdateSubscriptionWithBody(ctx context.Context, id SubscriptionUUID, version string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateSubscription /dss/subscriptions/{id}/{version}
	//
	// Update a Subscription.  The full content of the existing Subscription will be replaced with the provided information as only the most recent version is retained.
	//
	// Subscription notifications are only triggered by (and contain full information of) changes to, creation of, or deletion of, Entities referenced by or stored in the DSS; they do not involve any data transfer (such as remote ID telemetry updates) apart from Entity information.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PUT /dss/subscriptions/{id}/{version} (the `UpdateSubscription` operationId).
	UpdateSubscription(ctx context.Context, id SubscriptionUUID, version string, body UpdateSubscriptionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SearchFlights /uss/flights
	//
	// Retrieve basic flight information from a remote ID service provider to meet remote ID requirements.  This endpoint will be polled by remote ID display providers to display basic aircraft activity near a user in real time.  All flights that have any recent positions (past [NetUasInAreaWindow] seconds) inside the requested view and time frame must be returned.
	//
	// Corresponds with GET /uss/flights (the `SearchFlights` operationId).
	SearchFlights(ctx context.Context, params *SearchFlightsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetFlightDetails /uss/flights/{id}/details
	//
	// Retrieve details of a flight from a remote ID service provider to meet remote ID requirements.
	//
	// Corresponds with GET /uss/flights/{id}/details (the `GetFlightDetails` operationId).
	GetFlightDetails(ctx context.Context, id RIDFlightID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostIdentificationServiceAreaWithBody /uss/identification_service_areas/{id}
	//
	// Hosted by a remote ID display provider using Subscriptions: publish new full information of an Identification Service Area to the host of this endpoint (usually because of instructions from the DSS triggered by a subscription).
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /uss/identification_service_areas/{id} (the `PostIdentificationServiceArea` operationId).
	PostIdentificationServiceAreaWithBody(ctx context.Context, id EntityUUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostIdentificationServiceArea /uss/identification_service_areas/{id}
	//
	// Hosted by a remote ID display provider using Subscriptions: publish new full information of an Identification Service Area to the host of this endpoint (usually because of instructions from the DSS triggered by a subscription).
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /uss/identification_service_areas/{id} (the `PostIdentificationServiceArea` operationId).
	PostIdentificationServiceArea(ctx context.Context, id EntityUUID, body PostIdentificationServiceAreaJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// SearchIdentificationServiceAreas /dss/identification_service_areas
//
// Retrieve all Identification Service Areas in the DAR for a given area during the given time.  Note that some Identification Service Areas returned may lie entirely outside the requested area.
//
// Corresponds with GET /dss/identification_service_areas (the `SearchIdentificationServiceAreas` operationId).
func (c *StdClient) SearchIdentificationServiceAreas(ctx context.Context, params *SearchIdentificationServiceAreasParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSearchIdentificationServiceAreasRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateSubscriptionWithBody /dss/subscriptions/{id}
//
// Create a subscription.  This call will fail if a Subscription with the same ID already exists.
//
// Subscription notifications are only triggered by (and contain full information of) changes to, creation of, or deletion of, Entities referenced by or stored in the DSS; they do not involve any data transfer (such as remote ID telemetry updates) apart from Entity information.
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /dss/subscriptions/{id} (the `CreateSubscription` operationId).
func (c *StdClient) CreateSubscriptionWithBody(ctx context.Context, id SubscriptionUUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateSubscriptionRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateSubscription /dss/subscriptions/{id}
//
// Create a subscription.  This call will fail if a Subscription with the same ID already exists.
//
// Subscription notifications are only triggered by (and contain full information of) changes to, creation of, or deletion of, Entities referenced by or stored in the DSS; they do not involve any data transfer (such as remote ID telemetry updates) apart from Entity information.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PUT /dss/subscriptions/{id} (the `CreateSubscription` operationId).
func (c *StdClient) CreateSubscription(ctx context.Context, id SubscriptionUUID, body CreateSubscriptionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateSubscriptionRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteSubscription /dss/subscriptions/{id}/{version}
//
// Delete a subscription.
//
// Corresponds with DELETE /dss/subscriptions/{id}/{version} (the `DeleteSubscription` operationId).
func (c *StdClient) DeleteSubscription(ctx context.Context, id SubscriptionUUID, version string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteSubscriptionRequest(c.Server, id, version)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpdateSubscriptionWithBody /dss/subscriptions/{id}/{version}
//
// Update a Subscription.  The full content of the existing Subscription will be replaced with the provided information as only the most recent version is retained.
//
// Subscription notifications are only triggered by (and contain full information of) changes to, creation of, or deletion of, Entities referenced by or stored in the DSS; they do not involve any data transfer (such as remote ID telemetry updates) apart from Entity information.
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /dss/subscriptions/{id}/{version} (the `UpdateSubscription` operationId).
func (c *StdClient) UpdateSubscriptionWithBody(ctx context.Context, id SubscriptionUUID, version string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateSubscriptionRequestWithBody(c.Server, id, version, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpdateSubscription /dss/subscriptions/{id}/{version}
//
// Update a Subscription.  The full content of the existing Subscription will be replaced with the provided information as only the most recent version is retained.
//
// Subscription notifications are only triggered by (and contain full information of) changes to, creation of, or deletion of, Entities referenced by or stored in the DSS; they do not involve any data transfer (such as remote ID telemetry updates) apart from Entity information.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PUT /dss/subscriptions/{id}/{version} (the `UpdateSubscription` operationId).
func (c *StdClient) UpdateSubscription(ctx context.Context, id SubscriptionUUID, version string, body UpdateSubscriptionJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateSubscriptionRequest(c.Server, id, version, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// SearchFlights /uss/flights
//
// Retrieve basic flight information from a remote ID service provider to meet remote ID requirements.  This endpoint will be polled by remote ID display providers to display basic aircraft activity near a user in real time.  All flights that have any recent positions (past [NetUasInAreaWindow] seconds) inside the requested view and time frame must be returned.
//
// Corresponds with GET /uss/flights (the `SearchFlights` operationId).
func (c *StdClient) SearchFlights(ctx context.Context, params *SearchFlightsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSearchFlightsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetFlightDetails /uss/flights/{id}/details
//
// Retrieve details of a flight from a remote ID service provider to meet remote ID requirements.
//
// Corresponds with GET /uss/flights/{id}/details (the `GetFlightDetails` operationId).
func (c *StdClient) GetFlightDetails(ctx context.Context, id RIDFlightID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetFlightDetailsRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostIdentificationServiceAreaWithBody /uss/identification_service_areas/{id}
//
// Hosted by a remote ID display provider using Subscriptions: publish new full information of an Identification Service Area to the host of this endpoint (usually because of instructions from the DSS triggered by a subscription).
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /uss/identification_service_areas/{id} (the `PostIdentificationServiceArea` operationId).
func (c *StdClient) PostIdentificationServiceAreaWithBody(ctx context.Context, id EntityUUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostIdentificationServiceAreaRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PostIdentificationServiceArea /uss/identification_service_areas/{id}
//
// Hosted by a remote ID display provider using Subscriptions: publish new full information of an Identification Service Area to the host of this endpoint (usually because of instructions from the DSS triggered by a subscription).
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /uss/identification_service_areas/{id} (the `PostIdentificationServiceArea` operationId).
func (c *StdClient) PostIdentificationServiceArea(ctx context.Context, id EntityUUID, body PostIdentificationServiceAreaJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostIdentificationServiceAreaRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewSearchIdentificationServiceAreasRequest constructs an http.Request for the SearchIdentificationServiceAreas method
func NewSearchIdentificationServiceAreasRequest(server string, params *SearchIdentificationServiceAreasParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/dss/identification_service_areas")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "area", params.Area, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "earliest_time", params.EarliestTime, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date-time"}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "latest_time", params.LatestTime, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date-time"}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateSubscriptionRequest calls the generic CreateSubscription builder with application/json body
func NewCreateSubscriptionRequest(server string, id SubscriptionUUID, body CreateSubscriptionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateSubscriptionRequestWithBody(server, id, "application/json", bodyReader)
}

// NewCreateSubscriptionRequestWithBody constructs an http.Request for the CreateSubscription method, with any body, and a specified content type
func NewCreateSubscriptionRequestWithBody(server string, id SubscriptionUUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/dss/subscriptions/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteSubscriptionRequest constructs an http.Request for the DeleteSubscription method
func NewDeleteSubscriptionRequest(server string, id SubscriptionUUID, version string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "version", version, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/dss/subscriptions/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateSubscriptionRequest calls the generic UpdateSubscription builder with application/json body
func NewUpdateSubscriptionRequest(server string, id SubscriptionUUID, version string, body UpdateSubscriptionJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateSubscriptionRequestWithBody(server, id, version, "application/json", bodyReader)
}

// NewUpdateSubscriptionRequestWithBody constructs an http.Request for the UpdateSubscription method, with any body, and a specified content type
func NewUpdateSubscriptionRequestWithBody(server string, id SubscriptionUUID, version string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "version", version, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/dss/subscriptions/%s/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewSearchFlightsRequest constructs an http.Request for the SearchFlights method
func NewSearchFlightsRequest(server string, params *SearchFlightsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/uss/flights")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "view", params.View, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if params.RecentPositionsDuration != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "recent_positions_duration", *params.RecentPositionsDuration, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "number", Format: "float"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetFlightDetailsRequest constructs an http.Request for the GetFlightDetails method
func NewGetFlightDetailsRequest(server string, id RIDFlightID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/uss/flights/%s/details", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostIdentificationServiceAreaRequest calls the generic PostIdentificationServiceArea builder with application/json body
func NewPostIdentificationServiceAreaRequest(server string, id EntityUUID, body PostIdentificationServiceAreaJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostIdentificationServiceAreaRequestWithBody(server, id, "application/json", bodyReader)
}

// NewPostIdentificationServiceAreaRequestWithBody constructs an http.Request for the PostIdentificationServiceArea method, with any body, and a specified content type
func NewPostIdentificationServiceAreaRequestWithBody(server string, id EntityUUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/uss/identification_service_areas/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *StdClient) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *StdClient) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// SearchIdentificationServiceAreasWithResponse /dss/identification_service_areas
	//
	// Retrieve all Identification Service Areas in the DAR for a given area during the given time.  Note that some Identification Service Areas returned may lie entirely outside the requested area.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /dss/identification_service_areas (the `SearchIdentificationServiceAreas` operationId).
	SearchIdentificationServiceAreasWithResponse(ctx context.Context, params *SearchIdentificationServiceAreasParams, reqEditors ...RequestEditorFn) (*SearchIdentificationServiceAreasReply, error)

	// CreateSubscriptionWithBodyWithResponse /dss/subscriptions/{id}
	//
	// Create a subscription.  This call will fail if a Subscription with the same ID already exists.
	//
	// Subscription notifications are only triggered by (and contain full information of) changes to, creation of, or deletion of, Entities referenced by or stored in the DSS; they do not involve any data transfer (such as remote ID telemetry updates) apart from Entity information.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /dss/subscriptions/{id} (the `CreateSubscription` operationId).
	CreateSubscriptionWithBodyWithResponse(ctx context.Context, id SubscriptionUUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateSubscriptionReply, error)

	// CreateSubscriptionWithResponse /dss/subscriptions/{id}
	//
	// Create a subscription.  This call will fail if a Subscription with the same ID already exists.
	//
	// Subscription notifications are only triggered by (and contain full information of) changes to, creation of, or deletion of, Entities referenced by or stored in the DSS; they do not involve any data transfer (such as remote ID telemetry updates) apart from Entity information.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /dss/subscriptions/{id} (the `CreateSubscription` operationId).
	CreateSubscriptionWithResponse(ctx context.Context, id SubscriptionUUID, body CreateSubscriptionJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateSubscriptionReply, error)

	// DeleteSubscriptionWithResponse /dss/subscriptions/{id}/{version}
	//
	// Delete a subscription.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /dss/subscriptions/{id}/{version} (the `DeleteSubscription` operationId).
	DeleteSubscriptionWithResponse(ctx context.Context, id SubscriptionUUID, version string, reqEditors ...RequestEditorFn) (*DeleteSubscriptionReply, error)

	// UpdateSubscriptionWithBodyWithResponse /dss/subscriptions/{id}/{version}
	//
	// Update a Subscription.  The full content of the existing Subscription will be replaced with the provided information as only the most recent version is retained.
	//
	// Subscription notifications are only triggered by (and contain full information of) changes to, creation of, or deletion of, Entities referenced by or stored in the DSS; they do not involve any data transfer (such as remote ID telemetry updates) apart from Entity information.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /dss/subscriptions/{id}/{version} (the `UpdateSubscription` operationId).
	UpdateSubscriptionWithBodyWithResponse(ctx context.Context, id SubscriptionUUID, version string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateSubscriptionReply, error)

	// UpdateSubscriptionWithResponse /dss/subscriptions/{id}/{version}
	//
	// Update a Subscription.  The full content of the existing Subscription will be replaced with the provided information as only the most recent version is retained.
	//
	// Subscription notifications are only triggered by (and contain full information of) changes to, creation of, or deletion of, Entities referenced by or stored in the DSS; they do not involve any data transfer (such as remote ID telemetry updates) apart from Entity information.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /dss/subscriptions/{id}/{version} (the `UpdateSubscription` operationId).
	UpdateSubscriptionWithResponse(ctx context.Context, id SubscriptionUUID, version string, body UpdateSubscriptionJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateSubscriptionReply, error)

	// SearchFlightsWithResponse /uss/flights
	//
	// Retrieve basic flight information from a remote ID service provider to meet remote ID requirements.  This endpoint will be polled by remote ID display providers to display basic aircraft activity near a user in real time.  All flights that have any recent positions (past [NetUasInAreaWindow] seconds) inside the requested view and time frame must be returned.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /uss/flights (the `SearchFlights` operationId).
	SearchFlightsWithResponse(ctx context.Context, params *SearchFlightsParams, reqEditors ...RequestEditorFn) (*SearchFlightsReply, error)

	// GetFlightDetailsWithResponse /uss/flights/{id}/details
	//
	// Retrieve details of a flight from a remote ID service provider to meet remote ID requirements.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /uss/flights/{id}/details (the `GetFlightDetails` operationId).
	GetFlightDetailsWithResponse(ctx context.Context, id RIDFlightID, reqEditors ...RequestEditorFn) (*GetFlightDetailsReply, error)

	// PostIdentificationServiceAreaWithBodyWithResponse /uss/identification_service_areas/{id}
	//
	// Hosted by a remote ID display provider using Subscriptions: publish new full information of an Identification Service Area to the host of this endpoint (usually because of instructions from the DSS triggered by a subscription).
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /uss/identification_service_areas/{id} (the `PostIdentificationServiceArea` operationId).
	PostIdentificationServiceAreaWithBodyWithResponse(ctx context.Context, id EntityUUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostIdentificationServiceAreaReply, error)

	// PostIdentificationServiceAreaWithResponse /uss/identification_service_areas/{id}
	//
	// Hosted by a remote ID display provider using Subscriptions: publish new full information of an Identification Service Area to the host of this endpoint (usually because of instructions from the DSS triggered by a subscription).
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /uss/identification_service_areas/{id} (the `PostIdentificationServiceArea` operationId).
	PostIdentificationServiceAreaWithResponse(ctx context.Context, id EntityUUID, body PostIdentificationServiceAreaJSONRequestBody, reqEditors ...RequestEditorFn) (*PostIdentificationServiceAreaReply, error)
}

type SearchIdentificationServiceAreasReply struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *SearchIdentificationServiceAreasResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *ErrorResponse
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *ErrorResponse
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *ErrorResponse
	// JSON413 the response for an HTTP 413 `application/json` response
	JSON413 *ErrorResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r SearchIdentificationServiceAreasReply) GetJSON200() *SearchIdentificationServiceAreasResponse {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r SearchIdentificationServiceAreasReply) GetJSON400() *ErrorResponse {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r SearchIdentificationServiceAreasReply) GetJSON401() *ErrorResponse {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r SearchIdentificationServiceAreasReply) GetJSON403() *ErrorResponse {
	return r.JSON403
}

// GetJSON413 returns the response for an HTTP 413 `application/json` response
func (r SearchIdentificationServiceAreasReply) GetJSON413() *ErrorResponse {
	return r.JSON413
}

// GetBody returns the raw response body bytes
func (r SearchIdentificationServiceAreasReply) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r SearchIdentificationServiceAreasReply) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SearchIdentificationServiceAreasReply) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SearchIdentificationServiceAreasReply) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateSubscriptionReply struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *PutSubscriptionResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *ErrorResponse
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *ErrorResponse
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *ErrorResponse
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *ErrorResponse
	// JSON429 the response for an HTTP 429 `application/json` response
	JSON429 *ErrorResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r CreateSubscriptionReply) GetJSON200() *PutSubscriptionResponse {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r CreateSubscriptionReply) GetJSON400() *ErrorResponse {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r CreateSubscriptionReply) GetJSON401() *ErrorResponse {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r CreateSubscriptionReply) GetJSON403() *ErrorResponse {
	return r.JSON403
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r CreateSubscriptionReply) GetJSON409() *ErrorResponse {
	return r.JSON409
}

// GetJSON429 returns the response for an HTTP 429 `application/json` response
func (r CreateSubscriptionReply) GetJSON429() *ErrorResponse {
	return r.JSON429
}

// GetBody returns the raw response body bytes
func (r CreateSubscriptionReply) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateSubscriptionReply) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateSubscriptionReply) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateSubscriptionReply) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteSubscriptionReply struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *DeleteSubscriptionResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *ErrorResponse
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *ErrorResponse
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *ErrorResponse
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *ErrorResponse
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *ErrorResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r DeleteSubscriptionReply) GetJSON200() *DeleteSubscriptionResponse {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r DeleteSubscriptionReply) GetJSON400() *ErrorResponse {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r DeleteSubscriptionReply) GetJSON401() *ErrorResponse {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r DeleteSubscriptionReply) GetJSON403() *ErrorResponse {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r DeleteSubscriptionReply) GetJSON404() *ErrorResponse {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r DeleteSubscriptionReply) GetJSON409() *ErrorResponse {
	return r.JSON409
}

// GetBody returns the raw response body bytes
func (r DeleteSubscriptionReply) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteSubscriptionReply) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteSubscriptionReply) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteSubscriptionReply) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UpdateSubscriptionReply struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *PutSubscriptionResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *ErrorResponse
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *ErrorResponse
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *ErrorResponse
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *ErrorResponse
	// JSON429 the response for an HTTP 429 `application/json` response
	JSON429 *ErrorResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r UpdateSubscriptionReply) GetJSON200() *PutSubscriptionResponse {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r UpdateSubscriptionReply) GetJSON400() *ErrorResponse {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r UpdateSubscriptionReply) GetJSON401() *ErrorResponse {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r UpdateSubscriptionReply) GetJSON403() *ErrorResponse {
	return r.JSON403
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r UpdateSubscriptionReply) GetJSON409() *ErrorResponse {
	return r.JSON409
}

// GetJSON429 returns the response for an HTTP 429 `application/json` response
func (r UpdateSubscriptionReply) GetJSON429() *ErrorResponse {
	return r.JSON429
}

// GetBody returns the raw response body bytes
func (r UpdateSubscriptionReply) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r UpdateSubscriptionReply) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateSubscriptionReply) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpdateSubscriptionReply) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type SearchFlightsReply struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *GetFlightsResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *ErrorResponse
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *ErrorResponse
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *ErrorResponse
	// JSON413 the response for an HTTP 413 `application/json` response
	JSON413 *ErrorResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r SearchFlightsReply) GetJSON200() *GetFlightsResponse {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r SearchFlightsReply) GetJSON400() *ErrorResponse {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r SearchFlightsReply) GetJSON401() *ErrorResponse {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r SearchFlightsReply) GetJSON403() *ErrorResponse {
	return r.JSON403
}

// GetJSON413 returns the response for an HTTP 413 `application/json` response
func (r SearchFlightsReply) GetJSON413() *ErrorResponse {
	return r.JSON413
}

// GetBody returns the raw response body bytes
func (r SearchFlightsReply) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r SearchFlightsReply) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SearchFlightsReply) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SearchFlightsReply) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetFlightDetailsReply struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *GetFlightDetailsResponse
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *ErrorResponse
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *ErrorResponse
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *ErrorResponse
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *ErrorResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetFlightDetailsReply) GetJSON200() *GetFlightDetailsResponse {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r GetFlightDetailsReply) GetJSON400() *ErrorResponse {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r GetFlightDetailsReply) GetJSON401() *ErrorResponse {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r GetFlightDetailsReply) GetJSON403() *ErrorResponse {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetFlightDetailsReply) GetJSON404() *ErrorResponse {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r GetFlightDetailsReply) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetFlightDetailsReply) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetFlightDetailsReply) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetFlightDetailsReply) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type PostIdentificationServiceAreaReply struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *ErrorResponse
	// JSON401 the response for an HTTP 401 `application/json` response
	JSON401 *ErrorResponse
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *ErrorResponse
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *ErrorResponse
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r PostIdentificationServiceAreaReply) GetJSON400() *ErrorResponse {
	return r.JSON400
}

// GetJSON401 returns the response for an HTTP 401 `application/json` response
func (r PostIdentificationServiceAreaReply) GetJSON401() *ErrorResponse {
	return r.JSON401
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r PostIdentificationServiceAreaReply) GetJSON403() *ErrorResponse {
	return r.JSON403
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r PostIdentificationServiceAreaReply) GetJSON409() *ErrorResponse {
	return r.JSON409
}

// GetBody returns the raw response body bytes
func (r PostIdentificationServiceAreaReply) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r PostIdentificationServiceAreaReply) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostIdentificationServiceAreaReply) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostIdentificationServiceAreaReply) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// SearchIdentificationServiceAreasWithResponse /dss/identification_service_areas
//
// Retrieve all Identification Service Areas in the DAR for a given area during the given time.  Note that some Identification Service Areas returned may lie entirely outside the requested area.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /dss/identification_service_areas (the `SearchIdentificationServiceAreas` operationId).
func (c *ClientWithResponses) SearchIdentificationServiceAreasWithResponse(ctx context.Context, params *SearchIdentificationServiceAreasParams, reqEditors ...RequestEditorFn) (*SearchIdentificationServiceAreasReply, error) {
	rsp, err := c.SearchIdentificationServiceAreas(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSearchIdentificationServiceAreasReply(rsp)
}

// CreateSubscriptionWithBodyWithResponse /dss/subscriptions/{id}
//
// Create a subscription.  This call will fail if a Subscription with the same ID already exists.
//
// Subscription notifications are only triggered by (and contain full information of) changes to, creation of, or deletion of, Entities referenced by or stored in the DSS; they do not involve any data transfer (such as remote ID telemetry updates) apart from Entity information.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /dss/subscriptions/{id} (the `CreateSubscription` operationId).
func (c *ClientWithResponses) CreateSubscriptionWithBodyWithResponse(ctx context.Context, id SubscriptionUUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateSubscriptionReply, error) {
	rsp, err := c.CreateSubscriptionWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateSubscriptionReply(rsp)
}

// CreateSubscriptionWithResponse /dss/subscriptions/{id}
//
// Create a subscription.  This call will fail if a Subscription with the same ID already exists.
//
// Subscription notifications are only triggered by (and contain full information of) changes to, creation of, or deletion of, Entities referenced by or stored in the DSS; they do not involve any data transfer (such as remote ID telemetry updates) apart from Entity information.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /dss/subscriptions/{id} (the `CreateSubscription` operationId).
func (c *ClientWithResponses) CreateSubscriptionWithResponse(ctx context.Context, id SubscriptionUUID, body CreateSubscriptionJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateSubscriptionReply, error) {
	rsp, err := c.CreateSubscription(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateSubscriptionReply(rsp)
}

// DeleteSubscriptionWithResponse /dss/subscriptions/{id}/{version}
//
// Delete a subscription.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /dss/subscriptions/{id}/{version} (the `DeleteSubscription` operationId).
func (c *ClientWithResponses) DeleteSubscriptionWithResponse(ctx context.Context, id SubscriptionUUID, version string, reqEditors ...RequestEditorFn) (*DeleteSubscriptionReply, error) {
	rsp, err := c.DeleteSubscription(ctx, id, version, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteSubscriptionReply(rsp)
}

// UpdateSubscriptionWithBodyWithResponse /dss/subscriptions/{id}/{version}
//
// Update a Subscription.  The full content of the existing Subscription will be replaced with the provided information as only the most recent version is retained.
//
// Subscription notifications are only triggered by (and contain full information of) changes to, creation of, or deletion of, Entities referenced by or stored in the DSS; they do not involve any data transfer (such as remote ID telemetry updates) apart from Entity information.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /dss/subscriptions/{id}/{version} (the `UpdateSubscription` operationId).
func (c *ClientWithResponses) UpdateSubscriptionWithBodyWithResponse(ctx context.Context, id SubscriptionUUID, version string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateSubscriptionReply, error) {
	rsp, err := c.UpdateSubscriptionWithBody(ctx, id, version, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateSubscriptionReply(rsp)
}

// UpdateSubscriptionWithResponse /dss/subscriptions/{id}/{version}
//
// Update a Subscription.  The full content of the existing Subscription will be replaced with the provided information as only the most recent version is retained.
//
// Subscription notifications are only triggered by (and contain full information of) changes to, creation of, or deletion of, Entities referenced by or stored in the DSS; they do not involve any data transfer (such as remote ID telemetry updates) apart from Entity information.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /dss/subscriptions/{id}/{version} (the `UpdateSubscription` operationId).
func (c *ClientWithResponses) UpdateSubscriptionWithResponse(ctx context.Context, id SubscriptionUUID, version string, body UpdateSubscriptionJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateSubscriptionReply, error) {
	rsp, err := c.UpdateSubscription(ctx, id, version, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateSubscriptionReply(rsp)
}

// SearchFlightsWithResponse /uss/flights
//
// Retrieve basic flight information from a remote ID service provider to meet remote ID requirements.  This endpoint will be polled by remote ID display providers to display basic aircraft activity near a user in real time.  All flights that have any recent positions (past [NetUasInAreaWindow] seconds) inside the requested view and time frame must be returned.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /uss/flights (the `SearchFlights` operationId).
func (c *ClientWithResponses) SearchFlightsWithResponse(ctx context.Context, params *SearchFlightsParams, reqEditors ...RequestEditorFn) (*SearchFlightsReply, error) {
	rsp, err := c.SearchFlights(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSearchFlightsReply(rsp)
}

// GetFlightDetailsWithResponse /uss/flights/{id}/details
//
// Retrieve details of a flight from a remote ID service provider to meet remote ID requirements.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /uss/flights/{id}/details (the `GetFlightDetails` operationId).
func (c *ClientWithResponses) GetFlightDetailsWithResponse(ctx context.Context, id RIDFlightID, reqEditors ...RequestEditorFn) (*GetFlightDetailsReply, error) {
	rsp, err := c.GetFlightDetails(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetFlightDetailsReply(rsp)
}

// PostIdentificationServiceAreaWithBodyWithResponse /uss/identification_service_areas/{id}
//
// Hosted by a remote ID display provider using Subscriptions: publish new full information of an Identification Service Area to the host of this endpoint (usually because of instructions from the DSS triggered by a subscription).
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /uss/identification_service_areas/{id} (the `PostIdentificationServiceArea` operationId).
func (c *ClientWithResponses) PostIdentificationServiceAreaWithBodyWithResponse(ctx context.Context, id EntityUUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostIdentificationServiceAreaReply, error) {
	rsp, err := c.PostIdentificationServiceAreaWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostIdentificationServiceAreaReply(rsp)
}

// PostIdentificationServiceAreaWithResponse /uss/identification_service_areas/{id}
//
// Hosted by a remote ID display provider using Subscriptions: publish new full information of an Identification Service Area to the host of this endpoint (usually because of instructions from the DSS triggered by a subscription).
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /uss/identification_service_areas/{id} (the `PostIdentificationServiceArea` operationId).
func (c *ClientWithResponses) PostIdentificationServiceAreaWithResponse(ctx context.Context, id EntityUUID, body PostIdentificationServiceAreaJSONRequestBody, reqEditors ...RequestEditorFn) (*PostIdentificationServiceAreaReply, error) {
	rsp, err := c.PostIdentificationServiceArea(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostIdentificationServiceAreaReply(rsp)
}

// ParseSearchIdentificationServiceAreasReply parses an HTTP response from a SearchIdentificationServiceAreasWithResponse call
func ParseSearchIdentificationServiceAreasReply(rsp *http.Response) (*SearchIdentificationServiceAreasReply, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SearchIdentificationServiceAreasReply{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SearchIdentificationServiceAreasResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	}

	return response, nil
}

// ParseCreateSubscriptionReply parses an HTTP response from a CreateSubscriptionWithResponse call
func ParseCreateSubscriptionReply(rsp *http.Response) (*CreateSubscriptionReply, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateSubscriptionReply{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PutSubscriptionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	}

	return response, nil
}

// ParseDeleteSubscriptionReply parses an HTTP response from a DeleteSubscriptionWithResponse call
func ParseDeleteSubscriptionReply(rsp *http.Response) (*DeleteSubscriptionReply, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteSubscriptionReply{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DeleteSubscriptionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseUpdateSubscriptionReply parses an HTTP response from a UpdateSubscriptionWithResponse call
func ParseUpdateSubscriptionReply(rsp *http.Response) (*UpdateSubscriptionReply, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateSubscriptionReply{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PutSubscriptionResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	}

	return response, nil
}

// ParseSearchFlightsReply parses an HTTP response from a SearchFlightsWithResponse call
func ParseSearchFlightsReply(rsp *http.Response) (*SearchFlightsReply, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SearchFlightsReply{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetFlightsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON413 = &dest

	}

	return response, nil
}

// ParseGetFlightDetailsReply parses an HTTP response from a GetFlightDetailsWithResponse call
func ParseGetFlightDetailsReply(rsp *http.Response) (*GetFlightDetailsReply, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetFlightDetailsReply{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetFlightDetailsResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParsePostIdentificationServiceAreaReply parses an HTTP response from a PostIdentificationServiceAreaWithResponse call
func ParsePostIdentificationServiceAreaReply(rsp *http.Response) (*PostIdentificationServiceAreaReply, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostIdentificationServiceAreaReply{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// SearchIdentificationServiceAreas /dss/identification_service_areas
	// (GET /dss/identification_service_areas)
	SearchIdentificationServiceAreas(w http.ResponseWriter, r *http.Request, params SearchIdentificationServiceAreasParams)
	// CreateSubscription /dss/subscriptions/{id}
	// (PUT /dss/subscriptions/{id})
	CreateSubscription(w http.ResponseWriter, r *http.Request, id SubscriptionUUID)
	// DeleteSubscription /dss/subscriptions/{id}/{version}
	// (DELETE /dss/subscriptions/{id}/{version})
	DeleteSubscription(w http.ResponseWriter, r *http.Request, id SubscriptionUUID, version string)
	// UpdateSubscription /dss/subscriptions/{id}/{version}
	// (PUT /dss/subscriptions/{id}/{version})
	UpdateSubscription(w http.ResponseWriter, r *http.Request, id SubscriptionUUID, version string)
	// SearchFlights /uss/flights
	// (GET /uss/flights)
	SearchFlights(w http.ResponseWriter, r *http.Request, params SearchFlightsParams)
	// GetFlightDetails /uss/flights/{id}/details
	// (GET /uss/flights/{id}/details)
	GetFlightDetails(w http.ResponseWriter, r *http.Request, id RIDFlightID)
	// PostIdentificationServiceArea /uss/identification_service_areas/{id}
	// (POST /uss/identification_service_areas/{id})
	PostIdentificationServiceArea(w http.ResponseWriter, r *http.Request, id EntityUUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// SearchIdentificationServiceAreas operation middleware
func (siw *ServerInterfaceWrapper) SearchIdentificationServiceAreas(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchIdentificationServiceAreasParams

	// ------------- Required query parameter "area" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "area", r.URL.Query(), &params.Area, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "area"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "area", Err: err})
		}
		return
	}

	// ------------- Required query parameter "earliest_time" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "earliest_time", r.URL.Query(), &params.EarliestTime, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "earliest_time"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "earliest_time", Err: err})
		}
		return
	}

	// ------------- Required query parameter "latest_time" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "latest_time", r.URL.Query(), &params.LatestTime, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "latest_time"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "latest_time", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchIdentificationServiceAreas(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSubscription operation middleware
func (siw *ServerInterfaceWrapper) CreateSubscription(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id SubscriptionUUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSubscription(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSubscription operation middleware
func (siw *ServerInterfaceWrapper) DeleteSubscription(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id SubscriptionUUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "version" -------------
	var version string

	err = runtime.BindStyledParameterWithOptions("simple", "version", r.PathValue("version"), &version, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "version", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSubscription(w, r, id, version)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSubscription operation middleware
func (siw *ServerInterfaceWrapper) UpdateSubscription(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id SubscriptionUUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "version" -------------
	var version string

	err = runtime.BindStyledParameterWithOptions("simple", "version", r.PathValue("version"), &version, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "version", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSubscription(w, r, id, version)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchFlights operation middleware
func (siw *ServerInterfaceWrapper) SearchFlights(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchFlightsParams

	// ------------- Required query parameter "view" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "view", r.URL.Query(), &params.View, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "view"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "view", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "recent_positions_duration" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "recent_positions_duration", r.URL.Query(), &params.RecentPositionsDuration, runtime.BindQueryParameterOptions{Type: "number", Format: "float"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "recent_positions_duration"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "recent_positions_duration", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchFlights(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFlightDetails operation middleware
func (siw *ServerInterfaceWrapper) GetFlightDetails(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id RIDFlightID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFlightDetails(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostIdentificationServiceArea operation middleware
func (siw *ServerInterfaceWrapper) PostIdentificationServiceArea(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id EntityUUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostIdentificationServiceArea(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/dss/identification_service_areas", wrapper.SearchIdentificationServiceAreas)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/uss/flights", wrapper.SearchFlights)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/uss/flights/{id}/details", wrapper.GetFlightDetails)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/dss/subscriptions/{id}", wrapper.CreateSubscription)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/dss/subscriptions/{id}/{version}", wrapper.DeleteSubscription)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/dss/subscriptions/{id}/{version}", wrapper.UpdateSubscription)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/uss/identification_service_areas/{id}", wrapper.PostIdentificationServiceArea)

	return m
}
