#!/usr/bin/env node
// The TypeScript types of this repository's own frame schemas (WP-21):
// the authority's extras of console/status/v1, track/telemetry/v1 and
// console/snapshot/v1 (schemas/picture/) and violation/v1
// (schemas/violation/), generated with json-schema-to-typescript into
// src/picture/generated/. The shapes several systems share are the lab's
// and reach the console through the kit's live client; only what this
// repository defines is generated here, and never written by hand.
//
// Each schema states its extras as `$defs.body` beside an `allOf` that
// points at the lab's schema by URL. The generator is given the body
// alone (with the schema's `$defs`, so local references resolve) and
// never fetches anything.
//
//   node scripts/gen-schemas.mjs           write the files
//   node scripts/gen-schemas.mjs --check   exit 1 when a file is missing or differs
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const web = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const repo = path.resolve(web, "..");
const OUT_DIR = path.join(web, "src/picture/generated");

/** Input schema (relative to the repository), output file, root type name. */
export const TARGETS = [
  { input: "schemas/picture/status/v1.json", output: "status.d.ts", name: "PictureStatusExtras" },
  { input: "schemas/picture/track/v1.json", output: "track.d.ts", name: "PictureTrackExtras" },
  { input: "schemas/picture/snapshot/v1.json", output: "snapshot.d.ts", name: "PictureSnapshotExtras" },
  { input: "schemas/violation/v1.json", output: "violation.d.ts", name: "ViolationBody" },
];

/** The body schema of a frame schema, standalone: no reference leaves the file. */
export function bodySchema(doc, name) {
  const defs = { ...(doc.$defs ?? {}) };
  let body = doc.properties?.body;
  if (body?.$ref === "#/$defs/body") body = defs.body;
  if (body === undefined || typeof body !== "object") throw new Error(`${doc.$id}: no body schema`);
  delete defs.body;
  const rest = { ...body };
  delete rest.$id;
  return { title: name, description: doc.description, ...rest, $defs: defs };
}

async function generate(t) {
  const raw = readFileSync(path.join(repo, t.input));
  const sha = createHash("sha256").update(raw).digest("hex");
  const doc = JSON.parse(raw.toString("utf8"));
  const banner = `// @generated by web/scripts/gen-schemas.mjs (json-schema-to-typescript) from ${t.input} ${sha}; do not edit`;
  const ts = await compile(bodySchema(doc, t.name), t.name, {
    bannerComment: banner,
    declareExternallyReferenced: true,
    strictIndexSignatures: true,
    format: false,
    $refOptions: { resolve: { external: false } },
  });
  return ts.endsWith("\n") ? ts : `${ts}\n`;
}

async function main(argv) {
  const check = argv.includes("--check");
  let stale = 0;
  mkdirSync(OUT_DIR, { recursive: true });
  for (const t of TARGETS) {
    const want = await generate(t);
    const file = path.join(OUT_DIR, t.output);
    let have = null;
    try {
      have = readFileSync(file, "utf8");
    } catch {
      have = null;
    }
    if (check) {
      if (have !== want) {
        console.error(`gen-schemas: ${path.relative(web, file)} is ${have === null ? "missing" : "out of date"} (from ${t.input}); run pnpm gen:schemas`);
        stale++;
      }
    } else {
      writeFileSync(file, want);
      console.log(`gen-schemas: wrote ${path.relative(web, file)} from ${t.input}`);
    }
  }
  if (check && stale === 0) console.log(`gen-schemas: ${TARGETS.length} files current`);
  return stale === 0 ? 0 : 1;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main(process.argv.slice(2)).then(
    (code) => (process.exitCode = code),
    (err) => {
      console.error(`gen-schemas: ${err instanceof Error ? err.message : String(err)}`);
      process.exitCode = 2;
    },
  );
}
