package zonesvc

// The console's zone editor (web/src/zones/editor/model.ts, WP-22)
// builds the ED-318 feature an author submits. Its member names are
// written in TypeScript, so they are checked here, where they are read:
// the request bodies the editor's tests pin
// (web/test/fixtures/zone-editor/*.json, regenerated by those tests) go
// through prepare, the validation POST /v1/zones and POST /v1/uspace run
// (uspace-core ed318.Parse, the period, the designation), and must be
// accepted. A body with one member misnamed is refused, naming it
// (E-01, E-03).

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/rootxkit/uspace-authority/internal/httpx"
)

const editorFixtures = "../../web/test/fixtures/zone-editor"

type editorBody struct {
	Feature        json.RawMessage `json:"feature"`
	ValidFrom      *time.Time      `json:"valid_from"`
	ValidTo        *time.Time      `json:"valid_to"`
	DesignatedFrom *time.Time      `json:"designated_from"`
	DesignatedTo   *time.Time      `json:"designated_to"`
	Designation    *struct {
		AirspaceName          string          `json:"airspace_name"`
		ServicesRequired      []string        `json:"services_required"`
		UASRequirements       json.RawMessage `json:"uas_requirements"`
		ServicePerformance    json.RawMessage `json:"service_performance"`
		OperationalConditions json.RawMessage `json:"operational_conditions"`
		AirspaceConstraints   json.RawMessage `json:"airspace_constraints"`
		AdjacentIDs           []string        `json:"adjacent_ids"`
		RiskAssessmentRef     string          `json:"risk_assessment_ref"`
		InControlledAirspace  bool            `json:"in_controlled_airspace"`
		ATSProviderID         string          `json:"ats_provider_id"`
		CISPID                string          `json:"cisp_id"`
		DesignationRef        string          `json:"designation_ref"`
		AIPRef                string          `json:"aip_ref"`
	} `json:"designation"`
}

// editorInput reads one fixture as the handler would hand it to prepare.
func editorInput(t *testing.T, raw []byte) (Dataset, *DraftInput) {
	t.Helper()
	var b editorBody
	if err := json.Unmarshal(raw, &b); err != nil {
		t.Fatalf("fixture: %v", err)
	}
	if b.Designation == nil {
		return DatasetZones, &DraftInput{Feature: b.Feature, ValidFrom: b.ValidFrom, ValidTo: b.ValidTo}
	}
	d := b.Designation
	return DatasetUSpace, &DraftInput{
		Feature: b.Feature, ValidFrom: b.DesignatedFrom, ValidTo: b.DesignatedTo,
		Designation: &Designation{
			Name: d.AirspaceName, ServicesRequired: d.ServicesRequired,
			UASRequirements: d.UASRequirements, ServicePerformance: d.ServicePerformance,
			OperationalConditions: d.OperationalConditions, AirspaceConstraints: d.AirspaceConstraints,
			AdjacentIDs: d.AdjacentIDs, RiskAssessmentRef: d.RiskAssessmentRef,
			InControlledAirspace: d.InControlledAirspace, ATSProviderID: d.ATSProviderID,
			CISPID: d.CISPID, DesignationRef: d.DesignationRef, AIPRef: d.AIPRef,
		},
	}
}

func editorFixtureFiles(t *testing.T) map[string][]byte {
	t.Helper()
	names, err := filepath.Glob(filepath.Join(editorFixtures, "*.json"))
	if err != nil {
		t.Fatal(err)
	}
	out := map[string][]byte{}
	for _, n := range names {
		raw, err := os.ReadFile(n)
		if err != nil {
			t.Fatal(err)
		}
		out[filepath.Base(n)] = raw
	}
	// The editor's tests write exactly these; a missing one proves nothing.
	for _, want := range []string{"polygon-full.json", "circle.json", "uspace.json"} {
		if _, ok := out[want]; !ok {
			t.Fatalf("%s missing from %s", want, editorFixtures)
		}
	}
	return out
}

func TestWebEditorBodiesAreAccepted(t *testing.T) {
	for name, raw := range editorFixtureFiles(t) {
		t.Run(name, func(t *testing.T) {
			ds, in := editorInput(t, raw)
			d, err := prepare(ds, in)
			if err != nil {
				t.Fatalf("refused: %v", err)
			}
			if d.Identifier == "" || len(d.Feature) == 0 {
				t.Fatalf("accepted without an identifier or a feature: %+v", d)
			}
		})
	}
}

func TestWebEditorMisnamedMemberIsRefused(t *testing.T) {
	files := editorFixtureFiles(t)
	for _, c := range []struct{ file, from, to, field string }{
		{"polygon-full.json", `"zoneAuthority"`, `"zoneAuthorities"`, "zoneAuthorities"},
		{"polygon-full.json", `"limitedApplicability"`, `"applicability"`, "applicability"},
		{"circle.json", `"subType"`, `"sub_type"`, "extent.subType"},
	} {
		t.Run(c.file+" "+c.to, func(t *testing.T) {
			raw := strings.Replace(string(files[c.file]), c.from, c.to, 1)
			if raw == string(files[c.file]) {
				t.Fatalf("%s not in %s", c.from, c.file)
			}
			ds, in := editorInput(t, []byte(raw))
			_, err := prepare(ds, in)
			if err == nil {
				t.Fatalf("%s accepted", c.to)
			}
			if !strings.Contains(err.Error(), c.field) && !strings.Contains(errorFields(err), c.field) {
				t.Fatalf("the refusal does not name %s: %v (%s)", c.field, err, errorFields(err))
			}
		})
	}
}

// errorFields is every field and reason of a refusal, for the message.
func errorFields(err error) string {
	p := httpx.ProblemFromError(err)
	var b strings.Builder
	for _, e := range p.Errors {
		b.WriteString(e.Field + ": " + e.Reason + "; ")
	}
	return b.String()
}
