#!/usr/bin/env bash
# Writes deploy/env/<process>.env.example, the catalogue of every
# variable each process (and migrate) reads, from the process's own
# `--help` (internal/config is the only source of configuration, so the
# help is the catalogue and cannot drift from it):
#
#   scripts/gen-env-catalog.sh [output directory]   (default deploy/env)
#
# Every line is a comment: a deployment copies what it sets into its
# AUTHORITY_ENV_FILE (deploy/staging.env.example is staging's). `make
# check-deploy` regenerates the catalogue into a scratch directory and
# fails on any difference from the committed one.
set -euo pipefail
cd "$(dirname "$0")/.."

GO="${GO:-go}"
out="${1:-deploy/env}"
mkdir -p "$out"

# catalogue <title> <help command...>: the help as commented env lines.
catalogue() {
  local title="$1"; shift
  {
    echo "# Every variable $title reads, generated by scripts/gen-env-catalog.sh"
    echo "# from its --help; do not edit. Defaults apply when a variable is unset;"
    echo "# (required) ones have none, (secret) ones belong in AUTHORITY_SECRETS_DIR."
    echo "#"
    "$@" | tr -d '\r' | awk '
      /^[A-Z][A-Z0-9_]* / || /^[A-Z][A-Z0-9_]*$/ {
        name = $1
        meta = ""
        if (index($0, "(") > 0) { meta = substr($0, index($0, "(")) }
        def = ""
        if (match(meta, /default [^;)]*/)) { def = substr(meta, RSTART + 8, RLENGTH - 8) }
        pending = 1
        next
      }
      /^    / && pending {
        sub(/^    /, "")
        print ""
        print "# " $0 (meta != "" ? " " meta : "")
        print "#" name "=" def
        pending = 0
      }
    '
  } > "$out/$title.env.example"
}

for p in api rid-ingest dp-poller manned-ingest detect tsdb-writer picture-ws; do
  catalogue "$p" "$GO" run "./cmd/$p" --help
done
catalogue migrate "$GO" run ./cmd/uspace-authority migrate --help
echo "gen-env-catalog: wrote $(find "$out" -name '*.env.example' | wc -l | tr -d ' ') catalogues to $out"
